### ISSUE TITLE
Sort `tmp/ymls` for SB posting order

### ISSUE THREAD

**Issue by jordansread** [jread-usgs/hyperscales-data-release#8]
Right now the SB files are in kind of a random order, making it a little harder for users to find what they want if they aren't using scripting. 

right now: 
```yaml
tmp/predictions_02_N48.00-49.00_W91.50-95.00.zip: 46a8692246b83d3821120b5330969e9c
tmp/predictions_23_N45.00-46.00_W89.00-89.50.zip: 652161f5a70b5ac32c902d73af5b10a4
tmp/predictions_07_N46.00-48.00_W92.00-93.00.zip: 2b27138532613230c0c05560454a9cf1
tmp/predictions_35_N44.00-45.00_W91.00-93.50.zip: cb9a18d6487846e89a1f237e97ef9ab3
tmp/predictions_10_N46.00-48.00_W89.00-90.00.zip: 0061d742d475cf22034dd2fc9fb48a2f
tmp/predictions_22_N40.50-45.50_W89.50-91.00.zip: c2533bb8c43786359f5b5ae0454f0d66
tmp/predictions_30_N40.50-41.50_W84.50-89.50.zip: 0c230e33f65ef4e904c62b012d71bf9b
```

and SB:
![image](https://user-images.githubusercontent.com/2349007/72220523-15885e80-3517-11ea-9e12-136adf99defb.png)

seems we'd just need to sort in reverse order of how we want them to show on SB.
